#!/bin/bash

function car(){
st1=" *** "
st2="*****"
st3=" * * "
for ((i=0;i<$1;i=$i+1))
do
    st1=" $st1"
    st2=" $st2"
    st3=" $st3"
done
echo -en "$st1\n$st2\n$st3\r\033[2A"
}

for ((i=0;i<50;i=$i+1))
do
    car $i
    sleep 0.2
done

